database_file: "./db/matrix.db"
menu_program: "wofi --show drun"
fov: 45.0
zFar: 400.0
key_mappings:
  screenshot: "p"
  toggle_cursor: "f"
  quit: "escape"
  super_modifier: "super"
  debug_mesh: ","
  select: "e"
  unfocus_app: "e"
  move_forward: "w"
  move_back: "s"
  move_left: "a"
  move_right: "d"
